name: Build and Deploy

on:
  push:
    branches:
      - main # 监视推送到主分支的操作

jobs:
  build:
    runs-on: ubuntu-latest # 使用 GitHub 提供的 Ubuntu 虚拟机

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # 设置 Node.js 版本，可以根据需要更改

      # 3. 设置 pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "8" # 设置 pnpm 版本

      # 4. 安装依赖
      - name: Install dependencies
        run: pnpm install # 使用 pnpm 安装依赖

      # 5. 构建项目
      - name: Build the project
        run: CI=false pnpm run build # 关闭 CI 环境变量，避免警告作为错误，使用 pnpm 构建

      # 6. 设置 SSH 密钥，生成私匙.
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }} # 从 GitHub Secrets 中获取 SSH 私钥

      # 7. 添加服务器的 SSH 公钥到 known_hosts
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts  # 获取并添加服务器公钥

      # 8. 上传构建文件到服务器
      - name: Deploy to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }} # 从 GitHub Secrets 中获取服务器用户名
          SERVER_HOST: ${{ secrets.SERVER_HOST }} # 从 GitHub Secrets 中获取服务器 IP 地址
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }} # 从 GitHub Secrets 中获取部署目标目录
        run: |
          echo "Uploading build to server..."
          tar -czf build.tar.gz build  # 将构建文件打包成 tar.gz 文件
          scp build.tar.gz $SERVER_USER@$SERVER_HOST:$DEPLOY_DIR  # 使用 SCP 上传文件到服务器
          ssh $SERVER_USER@$SERVER_HOST "cd $DEPLOY_DIR && tar -xzf build.tar.gz && rm -f build.tar.gz"  # 在服务器上解压并部署构建文件

      # 9. 构建 Docker 镜像并运行
      - name: Build and run Docker container
        run: |
          ssh $SERVER_USER@$SERVER_HOST << 'EOF'
            cd $DEPLOY_DIR
            docker build -t ron-blob .
            docker run -d -p 8080:80 --name ron-blob ron-blob
          EOF
